# Generated by Django 3.2.13 on 2022-05-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('WareHouseId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=215)),
                ('Address', models.TextField()),
            ],
        ),
    ]
