# Generated by Django 3.2.13 on 2022-05-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Assigned_Warehouse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryDiscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrival', models.DateTimeField(blank=True)),
                ('Dispatch', models.DateTimeField(blank=True)),
                ('Item_Name', models.CharField(max_length=215)),
                ('Brand', models.CharField(max_length=215)),
                ('Desciprion', models.CharField(blank=True, max_length=215)),
                ('Quantity', models.IntegerField()),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=215, verbose_name='USD$')),
                ('Inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventorysheet')),
            ],
        ),
    ]
