# Generated by Django 3.2.13 on 2022-05-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_inventorydiscription_inventorysheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydiscription',
            name='Desciprion',
            field=models.CharField(blank=True, max_length=215, null=True),
        ),
        migrations.AlterField(
            model_name='inventorydiscription',
            name='Dispatch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
