# Generated by Django 3.2.13 on 2022-05-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20220509_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydiscription',
            name='Arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
