# Generated by Django 3.2.13 on 2022-05-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_inventorydiscription_arrival'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorydiscription',
            old_name='Inventory_id',
            new_name='Inventory_sheet',
        ),
    ]
