# Generated by Django 3.2.13 on 2022-05-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_rename_inventory_id_inventorydiscription_inventory_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysheet',
            name='Assigned_Warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.warehouse'),
        ),
    ]
